package Swing;//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import Exceptions.ServiceLegajoNoExsiteException;
import Main.PanelManager;
import Services.AlumnoServicio;
import Swing.Tablas.AlumnoTableModel;


import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;

public class Inicio_Swing extends JPanel {

    private PanelManager panelManager;
    private AlumnoServicio alumnoServicio;
    private AlumnoTableModel modelo;
    private JTable tabla;
    private JScrollPane scrollPane;

    public Inicio_Swing(PanelManager m){
        super();
        this.panelManager = m;
    }


    public void armarParcialSwing() {
        this.setLayout(new FlowLayout());
        setLayout (null);
        //componentes del JFrame
        JButton buttonCrearAlumno = new JButton("Crear Alumno");
        JButton buttonEditarAlumno = new JButton("Editar Alumno");
        JButton buttonBorrarAlumno = new JButton("Borrar Alumno");
        JButton buttonTabla = new JButton ("Actualizar Tabla Alumnos");
        JButton buttonExit = new JButton("Salir");


        modelo = new AlumnoTableModel();
        tabla = new JTable(modelo);
        scrollPane = new JScrollPane(tabla);

        buttonTabla.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                try {
                    alumnoServicio = new AlumnoServicio();
                    modelo.setContenido(alumnoServicio.listarAlumnos());
                    modelo.fireTableDataChanged();
                } catch (ServiceLegajoNoExsiteException serviceLegajoNoExsiteException) {
                    serviceLegajoNoExsiteException.printStackTrace();
                }

            }
        });

        buttonCrearAlumno.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                panelManager.mostrarPanelCreacionAlumno();
            }
        });

        buttonBorrarAlumno.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                panelManager.mostrarPanelEliminarAlumno();
            }
        });

        buttonEditarAlumno.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                panelManager.mostrarPanelProfesor();
            }
        });

        buttonExit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int exit = JOptionPane.showConfirmDialog(null, "Esta seguro que quiere salir?" , null, JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
                if (exit == JOptionPane.YES_OPTION)
                {
                    System.exit(0);
                }
            }
        });





        //agrego componentes al JFrame (Mismo que hacer frame.add(XXX))
        add(buttonCrearAlumno);
        add(buttonEditarAlumno);
        add(buttonBorrarAlumno);
        add(buttonExit);
        add(buttonTabla);
        add(scrollPane);

        //ubico componentes en JFrame
        buttonCrearAlumno.setBounds(65, 55, 155, 60);
        buttonEditarAlumno.setBounds(65, 155, 155, 60);
        buttonBorrarAlumno.setBounds(65, 255, 155, 60);
        buttonExit.setBounds(65, 455, 120, 45);
        buttonTabla.setBounds(65, 355, 155, 60);
        scrollPane.setBounds(250, 55, 655, 460);
    }


}