package Swing;//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import Main.PanelManager;
import Entidades.Alumno;
import Main.DAO.AlumnoDAOH2Impl;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class Inicio_Swing extends JPanel {

    private PanelManager panelManager;

    public Inicio_Swing(PanelManager m){
        super();
        this.panelManager = m;
    }

    //Cuando reinicio la tabla lo que hago es borrarla y luego crearla nuevamente
    public void reiniciarTabla(DefaultTableModel modeloTabla ){
        eliminarAlumnosTabla(modeloTabla);
        AlumnoDAOH2Impl alumnoDAO = new AlumnoDAOH2Impl();
        for(Alumno a : alumnoDAO.listaTodosLosAlumnos()){
            modeloTabla.addRow(new Object[]{
                    a.getLegajo(),
                    a.getNombre(),
                    a.getApellido(),
            });
        }
    }

    public void eliminarAlumnosTabla(DefaultTableModel modeloTabla){
        AlumnoDAOH2Impl alumnoDAO = new AlumnoDAOH2Impl();
        modeloTabla.setRowCount(0);
    }

    public void armarParcialSwing() {

        //componentes del JFrame
        JButton buttonCrearAlumno = new JButton("Crear Alumno");
        JButton buttonEditarAlumno = new JButton("Editar Alumno");
        JButton buttonBorrarAlumno = new JButton("Borrar Alumno");
        JButton buttonTabla = new JButton ("Actualizar Tabla Alumnos");
        JButton buttonExit = new JButton("Salir");
        JTable tabla = new JTable();
        DefaultTableModel modeloTabla = new DefaultTableModel();
        JScrollPane scrollPane = new JScrollPane();
        setLayout(null); // para poder ubicar libremente los componentes en JFrame

        //Listeners de los botones
        buttonTabla.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                reiniciarTabla(modeloTabla);
            }
        });

        buttonCrearAlumno.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                panelManager.mostrarPanelCreacionAlumno();
            }
        });

        buttonBorrarAlumno.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                panelManager.mostrarPanelEliminarAlumno();
            }
        });

        buttonEditarAlumno.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                panelManager.mostrarPanelEditarAlumno();
            }
        });

        buttonExit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int exit = JOptionPane.showConfirmDialog(null, "Esta seguro que quiere salir?" , null, JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
                if (exit == JOptionPane.YES_OPTION)
                {
                    System.exit(0);
                }
            }
        });


        //Codigo creacion y display de tabla de entidad Alumno
        scrollPane.setViewportView(tabla);
        modeloTabla.setColumnIdentifiers(new Object[]{"LEGAJO", "NOMBRE", "APELLIDO"});
        tabla.setModel(modeloTabla);
        tabla.setEnabled(false);
        tabla.setDefaultEditor(Object.class, null);
        modeloTabla.setRowCount(0);


        //agrego componentes al JFrame (Mismo que hacer frame.add(XXX))
        add(buttonCrearAlumno);
        add(buttonEditarAlumno);
        add(buttonBorrarAlumno);
        add(buttonExit);
        add(buttonTabla);
        add(scrollPane);

        //ubico componentes en JFrame
        buttonCrearAlumno.setBounds(65, 55, 155, 60);
        buttonEditarAlumno.setBounds(65, 155, 155, 60);
        buttonBorrarAlumno.setBounds(65, 255, 155, 60);
        buttonExit.setBounds(65, 455, 120, 45);
        buttonTabla.setBounds(65, 355, 155, 60);
        scrollPane.setBounds(250, 55, 655, 460);
    }


}